apiVersion: apps/v1
kind: Deployment
metadata:
  name: adder
  labels:
    app: adder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adder
  template:
    metadata:
      labels:
        app: adder
    spec:
      containers:
      - name: adder
        image: stravinskaiteg/hacalculator_test:adder
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parser
  labels:
    app: parser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parser
  template:
    metadata:
      labels:
        app: parser
    spec:
      containers:
      - name: parser
        image: stravinskaiteg/hacalculator_test:parser_v4
        ports:
        - containerPort: 80