apiVersion: v1
kind: Service
metadata:
  name: adder
spec:
  selector:
    app: adder
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: parser
spec:
  selector:
    app: parser
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: subtractor
spec:
  selector:
    app: subtractor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: multiplier
spec:
  selector:
    app: multiplier
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: divider
spec:
  selector:
    app: divider
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80